name: Flutter CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: stable
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze --no-pub
      - run: flutter test
